name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          path: repository
      - name: Build and test workspace
        uses: ichiro-its/ros2-build-and-test-action@main
        with:
          ros2-distro: humble
