name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 6 * * *'

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distribution: "foxy"
            os: "ubuntu-20.04"
          - ros_distribution: "galactic"
            os: "ubuntu-20.04"
          - ros_distribution: "humble"
            os: "ubuntu-22.04"
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.ros_distribution }}
      - uses: codecov/codecov-action@v3
        with:
          file: ros_ws/lcov/total_coverage.info
